#!/usr/bin/env python3
import sys
import pathlib
import shutil

# Configuration
CONFIG_PATH = pathlib.Path.home() / ".config" / "nvim"
QUERY_PATH = CONFIG_PATH / "queries" / "qxq"
LAZY_PLUGINS_PATH = CONFIG_PATH / "lua" / "plugins"
FTDETECT_PATH = CONFIG_PATH / "after" / "ftdetect"
NVIM_PARSER_DIR = pathlib.Path.home() / ".local" / "share" / "nvim" / "site" / "parser"
NVIM_PARSER_BINARY = NVIM_PARSER_DIR / "qxq.so"

# Current project path
CURRENT_DIR = pathlib.Path(__file__).parent.resolve()

# Minimal spec just to tell Treesitter that 'qxq' is a valid language
LAZY_VIM_SPEC = f"""-- Generated by qxq/manage_nvim.py
return {{
  {{
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      local parsers = require("nvim-treesitter.parsers")
      local parser_config = (type(parsers.get_parser_configs) == "function") 
                            and parsers.get_parser_configs() 
                            or parsers
      
      parser_config.qxq = {{
        install_info = {{
          url = "{CURRENT_DIR}",
          files = {{"src/parser.c"}},
        }},
        filetype = "qxq",
      }}
      
      return opts
    end,
  }},
}}
"""

FTDETECT_CONTENT = """-- Generated by qxq/manage_nvim.py
vim.filetype.add({
  extension = {
    qxq = "qxq",
  },
})
"""

HIGHLIGHT_SCM_CONTENT = """-- Generated by qxq/manage_nvim.py
; Keywords
"let" @keyword
"rec" @keyword
"fn" @keyword
"end" @keyword
"if" @keyword
"then" @keyword
"else" @keyword

; Literals
(number) @number
(string) @string
(boolean) @boolean
(escape_sequence) @string.escape

; Comments
(comment) @comment

; Identifiers
(identifier) @variable
(let_binding name: (identifier) @variable.definition)
(function_definition (parameters (identifier) @variable.parameter))
(call_expression (identifier) @function.call)

; Operators
(operator) @operator
"@" @operator
":" @operator
"=" @operator
";" @punctuation.delimiter
"," @punctuation.delimiter

; Brackets
"(" @punctuation.bracket
")" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket
"{" @punctuation.bracket
"}" @punctuation.bracket

"""


def install_binary():
    NVIM_PARSER_DIR.mkdir(parents=True, exist_ok=True)

    # Possible source binary names
    possible_sources = ["parser.dylib", "parser.so", "qxq.so", "qxq.dylib"]
    found_source = None
    for src in possible_sources:
        src_path = CURRENT_DIR / src
        if src_path.exists():
            found_source = src_path
            break

    if found_source:
        print(f"Installing binary from {found_source} to {NVIM_PARSER_BINARY}")
        shutil.copy2(found_source, NVIM_PARSER_BINARY)
    else:
        print(
            "Warning: No compiled binary found. Please run 'just highlight-generate' first."
        )


def install():
    print("Installing qxq highlighting (binary-first approach)...")

    # 1. Binary
    install_binary()

    # 2. Queries
    QUERY_PATH.mkdir(parents=True, exist_ok=True)
    with open(QUERY_PATH / "highlights.scm", "w") as f:
        f.write(HIGHLIGHT_SCM_CONTENT)
    print(f"Created highlights in {QUERY_PATH}")

    # 3. Filetype detection
    FTDETECT_PATH.mkdir(parents=True, exist_ok=True)
    with open(FTDETECT_PATH / "qxq.lua", "w") as f:
        f.write(FTDETECT_CONTENT)
    print(f"Created ftdetect in {FTDETECT_PATH}")

    # 4. LazyVim Registration
    if LAZY_PLUGINS_PATH.exists():
        with open(LAZY_PLUGINS_PATH / "qxq_treesitter.lua", "w") as f:
            f.write(LAZY_VIM_SPEC)
        print(f"Created LazyVim spec in {LAZY_PLUGINS_PATH}")

    print("\nInstallation successful! Restart Neovim to apply changes.")


def uninstall():
    print("Uninstalling qxq highlighting...")

    # Remove config files
    paths_to_remove = [
        LAZY_PLUGINS_PATH / "qxq_treesitter.lua",
        FTDETECT_PATH / "qxq.lua",
        QUERY_PATH / "highlights.scm",
        NVIM_PARSER_BINARY,
    ]

    for p in paths_to_remove:
        if p.exists() or p.is_symlink():
            print(f"Removing {p}")
            p.unlink()

    # Clean up empty query dir
    if QUERY_PATH.exists() and not any(QUERY_PATH.iterdir()):
        QUERY_PATH.rmdir()

    print("Uninstallation successful.")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "uninstall":
        uninstall()
    else:
        install()
